[theme]
primaryColor = "#F63366" # Vibrant pink-ish
backgroundColor = "#FFFFFF" # White
secondaryBackgroundColor = "#f0f0f0" # Light gray
textColor = "#262730" # Dark gray
font = "Arial"
successColor = "#4CAF50" # Green 
warningColor = "#FFD700" # Gold
errorColor = "#DC3545" # Red
infoColor = "#007bff" # Light blue
codeColor = "#e91e63"
headerColor = "#f8f9fa"
headerFont = "Roboto"
headerFontSize = "2rem"
buttonColor = "#007bff" # Light blue