[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[client]
showErrorDetails = false
showWarningOnDirectExecution = true

[logger]
level = "info"
format = "%(asctime)s.%(msecs)03d %(message)s"
dateFormat = "%Y-%m-%d %H:%M:%S"

[runner]
magicEnabled = true
installTracer = false

[deprecation]
showfileUploaderEncoding = false
